### ISSUE TITLE
Version of jpmml-converter correspond to version of spark

### ISSUE THREAD

**Issue by GuoYL36** [jpmml/jpmml-converter#20]
Hi,  when I use jpmml-converter and jpmml-sparkml，the following bugs arise:
（1）jpmml-converter-1.3.9 ： Caused by: java.lang.ClassNotFoundException: org.jpmml.converter.HasNativeConfiguration
（2）jpmml-converter-1.4.6：  Caused by: java.lang.IllegalArgumentException: Expected Apache Spark ML version 2.4, got version 2.3 (2.3.1)

So, is there the relationship between jpmml-converter and spark?

Environment：spark-2.3.1

**Comment by vruusmann** [comment]
>  when I use jpmml-converter and jpmml-sparkml，the following bugs arise:

The JPMML-SparkML library includes a correct version of the JPMML-Converter library automatically. You don't need to re-configure anything.

> there the relationship between jpmml-converter and spark?

No, JPMML-Converter is completely independent of Apache Spark ML

> Environment：spark-2.3.1

See the JPMML-SparkML readme:
https://github.com/jpmml/jpmml-sparkml/tree/1.4.X#installation

This is the corresponding JPMML-Converter transitive dependency declaration:
https://github.com/jpmml/jpmml-sparkml/blob/1.4.19/pom.xml#L71-L75
